"use client";
// app/traps/page.tsx — Analyse pédagogique des pièges

import { useEffect, useState } from "react";
import Link from "next/link";
import { AlertTriangle, ChevronLeft, ChevronDown, ChevronRight, BookOpen } from "lucide-react";

type TrapData = { key: string; keyType: string; score: number; totalAttempts: number; wrongAttempts: number; recentQuestions: Array<{ id: string; prompt: string; trapFamily: string; explanationShort: string; difficulty: number; }>; };
const TRAPE_PEDAGOGY = { priorite_droite: { why: "On a tendance à croire qu'une voie plus large ou plus fréquentée est prioritaire. C'est faux.", rule: "En l'absence de signalisation, tout véhicule venant de ta droite est prioritaire.", examples: ["Deux routes de taille égale qui se croisent", "Une rue secondaire à droite d'un boulevard"] }, default: { why: "Ce point est fréquemment mal compris car la règle peut sembler contre-intuitive.", rule: "Relis attentivement ce thème dans le code officiel.", examples: [] } };
function getPedagogy(key) { const n = key.toLowerCase().replace(/ /g,"_"); for(const [k,v] of Object.entries(TRAPE_PEDAGOGY)){ if(n.includes(k)||k.includes(n))return v; } return TRAPE_PEDAGOGY.default; }
function TrapCard({trap,rank}){ const [open,setOpen]=useState(rank===0); const errorRate=trap.totalAttempts>0?Math.round((trap.wrongAttempts/trap.totalAttempts)*100):0; const pedagogy=getPedagogy(trap.key); const severity=errorRate>=60?"critical":errorRate>=35?"warn":"minor"; return(<div className={`rounded-2xl border-2 overflow-hidden ${severity==="critical"?"border-red-200":severity==="warn"?"border-orange-200":"border-yellow-200"}`}><button onClick={()=>setOpen(o=>!o)} className={`cw-full flex items-center gap-4 px-5 py-4 text-left transition-colors ${severity==="critical"?"bg-red-50 hover:bg-red-100":severity==="warn"?"bg-orange-50 hover:bg-orange-100":"bg-yellow-50 hover:bg-yellow-100"}`}><span className={`flex h-8 w-8 flex-shrink-0 items-center justify-center rounded-full text-sm font-bold ${severity==="critical"?"bg-red-500 text-white":severity==="warn"?"bg-orange-500 text-white":"bg-yellow-500 text-white"}`}>{rank+1}</span><div className="flex-1 min-w-0"><p className="font-semibold text-slate-800 capitalize text-sm">{trap.key.replace(/_/g," ")}</p><p className="text-xs text-slate-500 mt-0.5">{trap.wrongAttempts} erreur sur {trap.totalAttempts} tentative</p></div><div className="text-right"><p className={`font-bold text-lg ${severity==="critical"?"text-red-600":severity==="warn"?"text-orange-600":"text-yellow-700"}`}>{errorRate}%</p><p className="text-xs text-slate-400">d'erreur</p></div><ChevronDown className={`h-4 w-4 text-slate-400 transition-transform ${open?"rotate-180":""}`}/></button><div className="h-1 bg-white"><div className={`h-full ${severity==="critical"?"bg-red-400":severity==="warn"?"bg-orange-400":"bg-yellow-400"}`} style={{width:`${errorRate}%`}}/></div>{}{open&&(<div className="bg-white px-5 py-5 space-y-5 border-t border-slate-100"><div className="rounded-xl bg-slate-50 border border-slate-200 p-4"><p className="text-xs font-semibold text-slate-400 uppercase tracking-wide mb-2"><AlertTriangle className="h-3.5 w-3.5 inline mr-1"/>Pourquoi tu te trompes souvent</p><p className="text-sm text-slate-700 leading-relaxed">{pedagogy.why}</p></div><div className="rounded-xl bg-brand/5 border border-brand/20 p-4"><BookOpen className="h-3.5 w-3.5 inline mr-1 text-brand"/><p className="text-sm text-slate-800 font-medium leading-relaxed mt-1">{pedagogy.rule}</p></div><ul className="space-y-1.5">{pedagogy.examples.map((ex,i)=>(<li key={i} className="flex items-start gap-2 text-sm text-slate-600"><span className="text-brand mt-0.5">→</span><span>{ex}</span></li>))}</ul><div className="space-y-2">{trap.recentQuestions.slice(0,3).map(q=>(<div key={q.id} className="rounded-xl border border-slate-100 bg-slate-50 px-4 py-3"><p className="text-sm text-slate-700">{q.prompt}</p><p className="text-xs text-slate-400 mt-1.5 italic">{q.explanationShort}</p></div>))}</div></div>)}}</div>);}
export default function TrapsPage(){const [data,setData]=useState(null);const [loading,setLoading]=useState(true);useEffect(()=>{fetch("/api/traps").then(r=>r.json()).then(d=>{ssetData(d);setLoading(false);}).catch(()=>setLoading(false));},[]);return(<div className="min-h-screen bg-slate-50"><header className="sticky top-0 z-10 border-b border-slate-200 bg-white/90 backdrop-blur"><div className="mx-auto max-w-2xl flex items-center gap-3 px-6 py-3"><Link href="/dashboard" className="p-1.5 rounded-lg hover:bg-slate-100 text-slate-400 hover:text-slate-700 transition-colors"><ChevronLeft className="h-5 w-5"/></Link><h1 className="font-bold text-slate-900">Mes pièges</h1><Link href="/quiz" className="flex items-center gap-1.5 rounded-xl bg-brand px-4 py-2 text-sm font-semibold text-white hover:bg-brand-dark">Travailler ces pièges <ChevronRight className="h-3.5 w-3.5"/></Link></div></header><main className="mx-auto max-w-2xl px-6 py-8 space-y-4">{data?.traps.map((trap,i)=>(<TrapCard key={trap.key} trap={trap} rank={i}/>))}</main></div>);}
