import Link from "next/link";
import { XCircle, CheckCircle } from "lucide-react";
export const metadata={title:"Erreurs frequentes au code de la route",description:"Les idees recues qui font rater l'examen. Corrections claires et conseils."};
const ERRORS=[{wrong:"Je n'ai pas besoin de clignoter si personne ne me voit",right:"Le clignotant est obligatoire dans tous les cas.",theme:"Signalisation"},
{wrong:"Une route large = voie prioritaire",right:"La largeur n'a aucune valeur legale. Seuls les panneaux comptent.",theme:"Priorites"},
{wrong:"Je peux m'arreter n'importe ou si c'est bref",right:"L'arret est interdit devant un garage, sur un passage pieton, dans un tunnel.",theme:"Stationnement"},
{wrong:"Le telephone mains libres est autorise",right:"Tenir le telephone en main est interdit. Le kit mains libres est tolere.",theme:"Comportement"},
{wrong:"Je peux depasser sur une ligne discontinue",right:"Une ligne continue interdit le depassement. Une discontinue l'autorise sous conditions.",theme:"Marquage"},
{wrong:"Les feux de position suffisent de nuit",right:"Les feux de croisement sont obligatoires des la tombee de la nuit.",theme:"Eclairage"}];
export default function Page(){return(<main className="min-h-screen bg-slate-50"><nav className="border-b border-slate-200 bg-white"><div className="mx-auto flex max-w-3xl items-center justify-between px-6 py-4"><Link href="/" className="text-lg font-bold text-brand">Code Route</Link><Link href="/auth/register" className="rounded-lg bg-brand px-4 py-2 text-sm font-medium text-white">S'entrainer</Link></div></nav><div className="mx-auto max-w-3xl px-6 py-12"><h1 className="text-3xl font-bold text-slate-900 mb-8">Erreurs frequentes au code</h1><div className="space-y-4 mb-8">{ERRORS.map((e,i)=><div key={i} className="rounded-2xl border border-slate-200 bg-white overflow-hidden"><div className="px-5 py-2 bg-slate-50 border-b border-slate-100"><span className="text-xs font-medium text-slate-400 uppercase">{e.theme}</span></div><div className="p-5 space-y-3"><div className="flex items-start gap-3"><XCircle className="h-5 w-5 text-red-400 flex-shrink-0 mt-0.5"/><p className="text-sm text-slate-600 italic">&ldquo;{e.wrong}&rdquo;</p></div><div className="flex items-start gap-3"><CheckCircle className="h-5 w-5 text-brand flex-shrink-0 mt-0.5"/><p className="text-sm font-medium text-slate-800">{e.right}</p></div></div></div>)}</div><div className="rounded-2xl border border-slate-200 bg-white p-6 text-center"><Link href="/auth/register" className="inline-block rounded-xl bg-brand px-6 py-3 text-sm font-semibold text-white">S'entrainer gratuitement</Link></div></div></main>);}