import Link from "next/link";
export const metadata={title:"Questions pieges code de la route",description:"Les 8 familles de pieges les plus frequentes a l'examen du code de la route."};
const TRAPS=[{family:"Priorite implicite",tip:"La largeur n'a aucune valeur legale. Seuls les panneaux ou la priorite a droite comptent."},
{family:"Feu orange = accelerer",tip:"Le feu orange signifie s'arreter si possible. Accelerer est une infraction."},
{family:"Sortie de voie non publique",tip:"En sortant d'un parking, vous devez ceder le passage a tous."},
{family:"Distance d'arret vs freinage",tip:"Distance d'arret = reaction + freinage. A 90km/h : environ 70m."},
{family:"Clignotant obligatoire",tip:"Toujours obligatoire avant tout changement de direction."},
{family:"Depassement a droite",tip:"Interdit sauf si le vehicule devant tourne a gauche."},
{family:"Alcoolemie jeune conducteur",tip:"Permis probatoire : 0.2 g/L. Taux normal : 0.5 g/L."},
{family:"Feux de recul automatiques",tip:"Ils s'allument automatiquement en marche arriere."}];
export default function Page(){return(<main className="min-h-screen bg-slate-50"><nav className="border-b border-slate-200 bg-white"><div className="mx-auto flex max-w-3xl items-center justify-between px-6 py-4"><Link href="/" className="text-lg font-bold text-brand">Code Route</Link><Link href="/auth/register" className="rounded-lg bg-brand px-4 py-2 text-sm font-medium text-white">S'entrainer</Link></div></nav><div className="mx-auto max-w-3xl px-6 py-12"><h1 className="text-3xl font-bold text-slate-900 mb-8">Les questions pieges du code</h1><div className="space-y-4 mb-8">{TRAPS.map((t,i)=><div key={t.family} className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex items-start gap-3"><span className="flex h-7 w-7 flex-shrink-0 items-center justify-center rounded-full bg-orange-100 text-sm font-bold text-orange-600">{i+1}</span><div><p className="font-semibold text-slate-900">{t.family}</p><div className="mt-2 rounded-lg bg-brand/5 border border-brand/10 px-3 py-2"><p className="text-sm text-slate-700">{t.tip}</p></div></div></div></div>)}</div><div className="rounded-2xl border border-slate-200 bg-white p-6 text-center"><Link href="/auth/register" className="inline-block rounded-xl bg-brand px-6 py-3 text-sm font-semibold text-white">S'entrainer gratuitement</Link></div></div></main>);}